name: .NET Core

on:
  push:
    #Sequence of patterns matched against refs/heads
    branches:
      - master         # Push events on master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url: https://nuget.pkg.github.com/Marcel-B/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release
    - name: Pack
      run: dotnet pack -p:PackageVersion=2.1.2 -c Release -o ./
    - name: Publish to Nuget
      env:
        nuget_secret: ${{ secrets.NUGET }}
      run: dotnet nuget push *.nupkg -k $nuget_secret -s https://api.nuget.org/v3/index.json --skip-duplicate --timeout 360
  
    - name: Publish to GitHub
      env:
        super_secret: ${{ secrets.NEXUS }}
      #run: dotnet nuget push -s https://nexus.qaybe.de/repository/nuget-hosted/ -k $super_secret *.nupkg
      run: dotnet nuget push "*.nupkg" --skip-duplicate --no-symbols true
    - name: Clean Packages
      run: rm *.nupkg
